---
title: "Models"
output: html_notebook
---

### Load libraries

```{r}
library(plm)
library(lmtest)
library(dplyr)
```

### Fixed effects

```{r}
data <- read.csv("final_w456.csv")
#data <- read.csv("data_clean_w46.csv")
```

```{r}
# age squared
data$age_squared <- data$age^2
```

# work_horizon_change continuous

```{r}
fe_mod <- plm(eurod ~ work_horizon + work_horizon_change + age + I(age_squared) + partnerinhh + nb_children + gender + yrseducation, #+ jqi_monthly_earnings + jqi_skills_discretion + jqi_social_environment + jqi_physical_environment + jqi_intensity + jqi_prospects + jqi_working_time_quality + factor(country) + factor(isco),
               data = data,
               index = c("mergeid", "year"),
               model = "within")
coeftest(fe_mod, vcov. = vcovHC, type = "HC1")
```

# work_horizon_change binary (1 if >1)

```{r}
data$work_horizon_change_bin <- ifelse(data$work_horizon_change > 1, 1, 0)

fe_mod <- plm(eurod ~ work_horizon + work_horizon_change_bin + age + I(age_squared) + partnerinhh + nb_children + gender + yrseducation, #+ jqi_monthly_earnings + jqi_skills_discretion + jqi_social_environment + jqi_physical_environment + jqi_intensity + jqi_prospects + jqi_working_time_quality + factor(isco) + factor(country),
               data = data,
               index = c("mergeid", "year"),
               model = "within")
coeftest(fe_mod, vcov. = vcovHC, type = "HC1")
```

# work_horizon_change categoric

```{r}
data$work_horizon_change_cat <- cut(data$work_horizon_change, breaks = c(-Inf, 0, 1, 2, Inf), labels = c("0", "<1", "<2", "2+"), include.lowest = TRUE)


fe_mod <- plm(eurod ~ work_horizon + work_horizon_change_cat + age + I(age_squared) + partnerinhh + nb_children + gender + yrseducation + jqi_monthly_earnings + jqi_skills_discretion + jqi_social_environment + jqi_physical_environment + jqi_intensity + jqi_prospects + jqi_working_time_quality + factor(country) + factor(isco),
               data = data,
               index = c("mergeid", "year"),
               model = "within")
coeftest(fe_mod, vcov. = vcovHC, type = "HC1")
```



### DID

```{r}
data <- read.csv("data_clean_w46_common.csv")
```

```{r}
# age squared
data$age_squared <- data$age^2
```

```{r}
data$time = ifelse(data$year >= 2015, 1, 0)

#data <- data %>%
#  mutate(work_horizon_change = ifelse(time == 0, 0, work_horizon_change))

mergeids_to_treat <- data %>%
  filter(time == 1 & work_horizon_change > 1) %>%
  select(mergeid) %>%
  distinct()
data <- data %>%
  mutate(treated = ifelse(mergeid %in% mergeids_to_treat$mergeid, 1, 0))

data$did = data$time * data$treated
```

# Basic DID

```{r}
didreg = lm(eurod ~ treated + time + did, data = data)
summary(didreg)
```

# DID with demographics

```{r}
didreg = lm(eurod ~ treated + time + did + age + I(age_squared) + gender + nb_children + partnerinhh + yrseducation + work_horizon + work_horizon_change, data = data)
summary(didreg)
```

# DID with demographics and work quality indexes

```{r}
didreg = lm(eurod ~ treated + time + did + age + I(age_squared) + gender + nb_children + partnerinhh + yrseducation + work_horizon + work_horizon_change + jqi_monthly_earnings + jqi_skills_discretion + jqi_social_environment + jqi_physical_environment + jqi_intensity + jqi_prospects + jqi_working_time_quality, data = data)
summary(didreg)
```

# DID with demographics and work quality indexes and EuroD score in binary

```{r}
logit_reg <- glm(eurodcat ~ treated + time + did + age + I(age_squared) + gender + nb_children + partnerinhh + yrseducation + work_horizon + work_horizon_change + jqi_monthly_earnings + jqi_skills_discretion + jqi_social_environment + jqi_physical_environment + jqi_intensity + jqi_prospects + jqi_working_time_quality, data = data,
                 family = binomial(link = "logit"))

summary(logit_reg)
```

# DID for physcial environment above mean

```{r}
mean_physical_environment <- mean(data$jqi_physical_environment)
filtered_data <- data[data$jqi_physical_environment > mean_physical_environment, ]

didreg = lm(eurod ~ treated + time + did + age + I(age_squared) + gender + nb_children + partnerinhh + yrseducation + work_horizon + jqi_monthly_earnings + jqi_skills_discretion + jqi_social_environment + jqi_intensity + jqi_prospects + jqi_working_time_quality, data = filtered_data)
summary(didreg)
```
